repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: (autorl_landscape|tests)
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        files: (autorl_landscape|tests)
        language_version: python3.10
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: (autorl_landscape|tests)
        additional_dependencies: ['tomli'] # Needed to parse pyproject.toml
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.982
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [hydra-core==1.2.0, stable-baselines3==1.6.0, submitit==1.4.5]
  #       files: (autorl_landscape|tests)
  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: ./run-mypy.sh
  #       language: system
  #       types: [python]
  #       require_serial: true
  #       verbose: true
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: (autorl_landscape|tests)
        additional_dependencies: [Flake8-pyproject]
# - repo: meta
#   hooks:
#     - id: identity
#       files: (autorl_landscape|tests)
