# @package _global_

env:
  name: CartPole-v1
agent:
  name: DQN
  hps:
    batch_size: 64
    buffer_size: 100000
    exploration_fraction: 0.16
    gradient_steps: 128
    learning_starts: 1000
    policy: 'MlpPolicy'
    target_update_interval: 10
    train_freq: 256
eval:
  freq_eval_episodes: 10
  ls_eval_episodes: 20
  final_eval_episodes: 20
  final_eval_start: 0.95 # 95% progress (of total_timesteps) is first final eval
  final_eval_times: 3 # 3 final evals from final_eval_start until total_timesteps
viz: # visualization (e.g. in wandb)
  max_return: 500
  max_ep_length: 500
  hist_bins: 50
