# @package _global_

# defaults:
#   - agent: dqn
#   - env: cartpole

agent:
  name: DQN
  hps:
    policy: 'MlpPolicy'
    batch_size: 64
    buffer_size: 100000
    learning_starts: 1000
    target_update_interval: 10
    train_freq: 256
    gradient_steps: 128
    exploration_fraction: 0.16
    exploration_final_eps: 0.04
env:
  name: CartPole-v1
  total_timesteps: 100000
eval:
  freq_eval_interval: 5000
  freq_eval_episodes: 10
