# @package _global_

agent: # stuff for sb3
  name: DQN
  hps:
    batch_size: 64
    buffer_size: 100000
    exploration_final_eps: 0.04
    exploration_fraction: 0.16
    gradient_steps: 128
    learning_starts: 100
    policy: 'MlpPolicy'
    target_update_interval: 10
    train_freq: 256
  zoo_optimal_ls:
    learning_rate: 2.3e-3
    neg_gamma: 0.01
    nn_length: 3
    nn_width: 256
env: # stuff for the gym env
  name: CartPole-v1
  total_timesteps: 3000
eval:
  seed: 456
  freq_eval_interval: 100
  freq_eval_episodes: 10
  ls_eval_episodes: 10
  final_eval_episodes: 10
  final_eval_start: 0.95 # 95% progress (of total_timesteps) is first final eval
  final_eval_times: 3 # 3 final evals from final_eval_start until total_timesteps
viz: # visualization (e.g. in wandb)
  max_return: 500
  max_ep_length: 500
  hist_bins: 50
phases:
  - 1500
  # - 9000
  # - 7000
