# @package _global_

wandb:
  mode: online
slurm:
  cluster: local
  num_parallel: 4
  update_parameters: # for executor.update_parameters()
    timeout_min: 1000
    slurm_partition: dev
    gpus_per_node: 1
